allgods = dict(
    gods=dict(
        norse={
            "Odin": "The god of wisdom, war, and death.",
            "Thor": "The god of thunder and son of Odin.",
            "Loki": "The god of mischief and trickery.",
            "Frigg": "The goddess of love, fertility, and marriage.",
            "Balder": "The god of beauty, purity, and light.",
            "Hel": "The goddess of the underworld and daughter of Loki.",
            "Freyja": "The goddess of love, fertility, and war.",
            "Tyr": "The god of law and justice, and son of Odin.",
            "Heimdallr": "The god of light, guardian of the gods, and owner of the horn Gjallarhorn.",
            "Njord": "The god of the sea, fishing, and wealth.",
        },
        greek={
            "Zeus": "The god of the sky, thunder, and lightning.",
            "Poseidon": "The god of the sea, earthquakes, and horses.",
            "Hades": "The god of the underworld and the dead.",
            "Hera": "The goddess of marriage, women, and childbirth.",
            "Athena": "The goddess of wisdom, courage, and strategic warfare.",
            "Apollo": "The god of music, poetry, prophecy, and medicine.",
            "Artemis": "The goddess of the hunt, wild animals, and childbirth.",
            "Ares": "The god of war, violence, and bloodshed.",
            "Aphrodite": "The goddess of love, beauty, and sexuality.",
            "Hermes": "The god of commerce, thieves, and travelers.",
        },
        roman={
            "Jupiter": "The king of the gods and the god of the sky and thunder.",
            "Neptune": "The god of the sea and earthquakes.",
            "Pluto": "The god of the underworld and the dead.",
            "Juno": "The queen of the gods and the goddess of marriage.",
            "Minerva": "The goddess of wisdom, medicine, and crafts.",
            "Apollo": "The god of music, poetry, prophecy, and medicine.",
            "Diana": "The goddess of the hunt and the moon.",
            "Mars": "The god of war and agriculture.",
            "Venus": "The goddess of love, beauty, and fertility.",
            "Mercury": "The god of commerce, thieves, and travelers.",
        },
        hindu={
            "Brahma": "The creator god who is responsible for the creation of the universe.",
            "Vishnu": "The preserver god who is responsible for preserving the universe.",
            "Shiva": "The destroyer god who is responsible for destroying the universe in order to create a new one.",
            "Ganesha": "The god of wisdom, knowledge, and new beginnings.",
            "Krishna": "The god of love, compassion, and tenderness.",
            "Hanuman": "The god of strength, courage, and devotion.",
            "Kali": "The goddess of time, creation, and destruction.",
            "Lakshmi": "The goddess of wealth, prosperity, and fortune.",
            "Saraswati": "The goddess of knowledge, music, and art.",
            "Indra": "The god of war, weather, and thunderstorms.",
        },
        aztec={
            "Huitzilopochtli": "The god of war, sun, and human sacrifice.",
            "Quetzalcoatl": "The god of knowledge, wisdom, and wind.",
            "Tezcatlipoca": "The god of night, sorcery, and destiny.",
            "Xipe Totec": "The god of agriculture, vegetation, and seasons.",
            "Tlaloc": "The god of rain, fertility, and water.",
            "Coatlicue": "The goddess of fertility, earth, and life.",
            "Xochiquetzal": "The goddess of love, beauty, and fertility.",
            "Mictlantecuhtli": "The god of death and the underworld.",
            "Tonatiuh": "The god of the sun and the ruler of the heavens.",
            "Patecatl": "The god of healing, medicine, and fertility.",
        },
    ),
    cartoons=dict(
        disney={
            "Mickey Mouse": "The iconic mouse that started it all!",
            "Donald Duck": "A feisty and sometimes grumpy duck with a heart of gold.",
            "Goofy": "A lovable and goofy dog who always means well.",
            "Simba": "The young lion who becomes king of the Pride Lands.",
            "Ariel": "The curious mermaid who dreams of life on land.",
            "Aladdin": "The street rat who uses a genie to win the heart of a princess.",
            "Mulan": "The brave warrior who disguises herself as a man to fight for her country.",
            "Moana": "The adventurous teenager who sets sail on a mission to save her people.",
            "Elsa": "The queen of Arendelle who possesses magical ice powers.",
            "Buzz Lightyear": "The space ranger from the Toy Story franchise.",
        },
        warner_bros={
            "Bugs Bunny": "The iconic and mischievous rabbit known for his catchphrase 'What's up, Doc?'",
            "Daffy Duck": "The zany and often egotistical duck who frequently clashes with Bugs Bunny.",
            "Tweety Bird": "The cute and innocent canary who always manages to outsmart Sylvester the Cat.",
            "Porky Pig": "The stuttering pig who often serves as a sidekick to other Warner Bros. characters.",
            "Scooby-Doo": "The lovable and cowardly Great Dane who solves mysteries with his human friends.",
            "Road Runner": "The speedy bird who always manages to outsmart Wile E. Coyote.",
            "Wile E. Coyote": "The hapless and determined coyote who is always trying to catch the Road Runner.",
            "Marvin the Martian": "The alien who often tries to destroy the Earth with his ray gun.",
            "Elmer Fudd": "The bumbling and easily frustrated hunter who often chases Bugs Bunny.",
            "Speedy Gonzales": "The fast and clever mouse who always manages to outsmart his enemies.",
        },
        hannah_barbera={
            "Tom and Jerry": "The classic cat and mouse duo who engage in slapstick antics.",
            "Yogi Bear": "The picnic basket-stealing bear who lives in Jellystone Park.",
            "The Flintstones": "The modern Stone Age family who live in the town of Bedrock.",
            "The Jetsons": "The futuristic family who live in a world filled with robots and flying cars.",
            "Scooby-Doo": "The lovable and cowardly Great Dane who solves mysteries with his human friends.",
            "Hong Kong Phooey": "The kung fu-fighting dog who works as a janitor by day.",
            "Top Cat": "The streetwise alley cat who leads a gang of feline friends.",
            "Huckleberry Hound": "The easygoing and friendly blue dog who often sings and strums a guitar.",
            "Magilla Gorilla": "The friendly and lovable gorilla who lives in a pet store.",
            "Wally Gator": "The clever alligator who often outwits the humans around him.",
        },
        simpsons={
            "Homer Simpson": "The bumbling and lovable patriarch of the Simpson family.",
            "Marge Simpson": "The patient and long-suffering wife of Homer.",
            "Bart Simpson": "The mischievous and trouble-making son of the Simpson family.",
            "Lisa Simpson": "The intelligent and socially conscious daughter of the Simpson family.",
            "Maggie Simpson": "The youngest member of the Simpson family who is known for sucking on a pacifier.",
            "Grandpa Simpson": "The forgetful and often senile patriarch of the Simpson family.",
            "Ned Flanders": "The friendly and devoutly religious neighbor of the Simpson family.",
            "Mr. Burns": "The wealthy and conniving owner of the nuclear power plant where Homer works.",
            "Principal Skinner": "The strict and by-the-book principal of Springfield Elementary School.",
            "Krusty the Clown": "The cynical and jaded television clown who hosts a children's show.",
        },
        south_park={
            "Stan Marsh": "The everyman protagonist who often finds himself in bizarre situations.",
            "Kyle Broflovski": "The moral center of the show who is often at odds with his best friend Cartman.",
            "Eric Cartman": "The selfish and manipulative character who often serves as the show's antagonist.",
            "Kenny McCormick": "The quiet and often unfortunate character who frequently dies and comes back to life.",
            "Butters Stotch": "The naive and innocent character who often gets caught up in the other characters' schemes.",
            "Randy Marsh": "Stan's father who is often depicted as immature and irresponsible.",
            "Chef": "The singing and wise cafeteria worker at South Park Elementary.",
            "Timmy Burch": "The wheelchair-bound character who often says his own name as his only line of dialogue.",
            "Tweek Tweak": "The jittery and nervous character who is often paranoid and anxious.",
            "Jimmy Valmer": "The friendly and good-natured character who has a stutter and uses crutches.",
        },
    ),
    comics=dict(
        marvel={
            "Spider-Man": "A high school student named Peter Parker who gained spider-like abilities after being bitten by a radioactive spider.",
            "Iron Man": "A billionaire industrialist and genius inventor who creates a powered suit of armor to save the world.",
            "Captain America": "A World War II soldier who was given a super-soldier serum that gave him enhanced physical abilities.",
            "Hulk": "A scientist named Bruce Banner who transforms into a giant, green, superhuman monster when he becomes angry or stressed.",
            "Thor": "A god from Asgard who wields a mighty hammer and possesses incredible strength and durability.",
            "Black Widow": "A highly trained spy and assassin who is a member of the Avengers.",
            "Doctor Strange": "A brilliant but arrogant neurosurgeon who becomes a master of the mystic arts after a car accident leaves him unable to use his hands.",
            "Wolverine": "A mutant with retractable claws and a healing factor, who is a member of the X-Men.",
            "Deadpool": "A wisecracking mercenary with a healing factor and a penchant for breaking the fourth wall.",
            "Black Panther": "The king of Wakanda, who possesses enhanced strength, agility, and senses, as well as an advanced suit made of vibranium.",
        },
        dc={
            "Superman": "A superhero from the planet Krypton who possesses incredible strength, speed, and durability, as well as various sensory and vision powers.",
            "Batman": "A billionaire playboy and philanthropist who uses his wealth, physical prowess, and detective skills to fight crime as the Dark Knight of Gotham City.",
            "Wonder Woman": "An Amazon princess from the island of Themyscira who possesses superhuman strength, speed, and durability, as well as various weapons and abilities.",
            "The Flash": "A forensic scientist named Barry Allen who gains the power of superhuman speed after being struck by lightning.",
            "Green Lantern": "A member of an intergalactic police force called the Green Lantern Corps, who wields a ring that can create constructs of light.",
            "Aquaman": "The king of Atlantis, who possesses superhuman strength, durability, and aquatic abilities.",
            "Cyborg": "A former college athlete named Victor Stone who is transformed into a half-man, half-machine after a near-fatal accident.",
            "Shazam": "A young boy named Billy Batson who is granted the power to transform into a superhero with the wisdom of Solomon, the strength of Hercules, the stamina of Atlas, the power of Zeus, the courage of Achilles, and the speed of Mercury.",
            "Green Arrow": "A wealthy playboy and expert archer who fights crime as the Green Arrow.",
            "Martian Manhunter": "An alien from Mars who possesses a wide array of superhuman abilities, including shapeshifting, telepathy, and invisibility.",
        },
        image={
            "Spawn": "A former CIA agent named Al Simmons who is resurrected as a demonic creature with various supernatural powers.",
            "Savage Dragon": "A green-skinned, fin-headed police officer with superhuman strength and regenerative abilities.",
            "The Walking Dead": "A post-apocalyptic horror story about a group of survivors of a zombie outbreak.",
            "Invincible": "A teenage superhero named Mark Grayson who inherits his powers from his alien father.",
            "Chew": "A police detective named Tony Chu who gets psychic impressions from the things he eats.",
            "Saga": "An epic space opera about two soldiers from opposite sides of a galactic war who fall in love and have a child together, and their struggles to protect their family from various threats.",
            "Witchblade": "A supernatural artifact that can transform into a powerful weapon, and the various wielders who use it to fight evil.",
            "Hack/Slash": "A horror-comedy series about a young woman named Cassie Hack who hunts down and kills slashers like Jason Voorhees and Freddy Krueger.",
            "The Wicked + The Divine": "A story about a group of young people who discover that they are the reincarnated forms of various gods, and their struggles to deal with their newfound powers and responsibilities.",
            "Monstress": "A dark fantasy story set in an alternate 1900s Asia, about a teenage girl who is half-human, half-monster, and her journey to uncover the secrets of her past.",
        },
        vertigo={
            "Sandman": "A story about Dream of the Endless, one of seven beings who embody the fundamental concepts of existence, and his interactions with various mortal and immortal beings.",
            "Preacher": "A story about a Texas preacher named Jesse Custer who gains the power to make anyone do what he says, and his quest to find God and hold him accountable for abandoning his creation.",
            "Hellblazer": "A story about a chain-smoking, foul-mouthed British occult detective named John Constantine, who battles demons, angels, and other supernatural threats.",
            "Y: The Last Man": "A post-apocalyptic story about a young man named Yorick Brown, who is the last surviving human with a Y chromosome, and his travels to find his girlfriend and figure out why he survived.",
            "Fables": "A story about various fairy tale characters who have been exiled from their homelands and are living in a secret community in New York City, and their struggles to survive and deal with their pasts.",
            "100 Bullets": "A story about a mysterious organization called the Trust that gives people who have been wronged a gun and 100 untraceable bullets, and their choices about whether to seek revenge or not.",
            "Lucifer": "A story about the fallen angel Lucifer Morningstar, who abdicates his throne in Hell and opens a piano bar in Los Angeles, and his various interactions with mortals, immortals, and other beings.",
            "Transmetropolitan": "A cyberpunk story about a journalist named Spider Jerusalem who returns to the city after a five-year hiatus to cover the presidential election, and his battles against corrupt politicians, corporations, and other forces.",
            "Scalped": "A crime story set on a Native American reservation, about a young man named Dashiell Bad Horse who returns to the reservation after years away, and his involvement in various criminal activities and power struggles.",
            "DMZ": "A story about a journalist named Matty Roth who is trapped in a war zone in Manhattan after a second American civil war, and his experiences covering the conflict and its aftermath.",
        },
        dark_horse={
            "Hellboy": "A demon who was summoned to Earth by Nazis during World War II, but was rescued by a group of Allied soldiers and raised by a scientist, and his various adventures fighting supernatural threats.",
            "Sin City": "A series of interconnected neo-noir stories set in Basin City, a corrupt and violent metropolis, and its various inhabitants.",
            "Usagi Yojimbo": "A story about a ronin rabbit named Miyamoto Usagi who wanders feudal Japan, and his various encounters with samurai, ninja, and other characters.",
            "The Umbrella Academy": "A story about a group of superpowered siblings who were adopted by an eccentric billionaire and raised to save the world, and their struggles to deal with their dysfunctional family and various threats.",
            "B.P.R.D.": "A story about the Bureau for Paranormal Research and Defense, a secret government agency that investigates and fights supernatural threats, and its various agents.",
            "The Goon": "A story about a muscle-bound enforcer named the Goon who protects his town from various supernatural threats, including zombies, giant squid, and evil clowns.",
            "Aliens": "A series of stories set in the Alien universe, about various characters who encounter the titular creatures and other extraterrestrial threats.",
            "Lobster Johnson": "A pulp-style story about a vigilante hero from the 1930s who fights crime and supernatural threats, and his various interactions with other characters.",
            "Concrete": "A story about a man named Ron Lithgow who is transformed into a giant stone creature after a scientific experiment goes wrong, and his struggles to deal with his new body and his place in the world.",
            "Barb Wire": "A story about a bounty hunter named Barbara Kopetski who operates in a dystopian America that is recovering from a second civil war, and her various adventures and romances.",
        },
    ),
    philosophers=dict(
        lsd={
            "Robert Anton Wilson": "Robert Anton Wilson was an American author, futurist, and self-described agnostic mystic.",
            "Timothy Leary": "Timothy Leary was an American psychologist and writer, known for his advocacy of psychedelic drugs.",
            "Terence McKenna": "Terence McKenna was an American ethnobotanist, philosopher, and author, known for his work on the use of psychoactive plants.",
            "Ram Dass": "Ram Dass was an American spiritual teacher, psychologist, and author, known for his work on consciousness and spiritual practices.",
            "Aldous Huxley": "Aldous Huxley was an English writer and philosopher, known for his work on the use of psychedelic drugs and his dystopian novel 'Brave New World'.",
            "Alex Grey": "Alex Grey is an American artist and writer, known for his psychedelic artwork and his contributions to the study of consciousness.",
            "David Nichols": "David Nichols is an American pharmacologist and chemist, known for his research on the effects of psychedelic drugs on the brain.",
            "Rick Strassman": "Rick Strassman is an American psychiatrist and author, known for his research on the use of DMT as a psychedelic drug.",
            "Stanislav Grof": "Stanislav Grof is a Czech psychiatrist and author, known for his work on transpersonal psychology and the therapeutic use of LSD.",
            "Jeremy Narby": "Jeremy Narby is a Swiss anthropologist and author, known for his work on the shamanic use of ayahuasca and the study of indigenous knowledge systems.",
        },
        ancient={
            "Plato": "Plato was a Greek philosopher and student of Socrates. He founded the Academy in Athens and wrote many philosophical dialogues.",
            "Aristotle": "Aristotle was a Greek philosopher and student of Plato. He wrote extensively on a range of topics, including ethics, politics, and metaphysics.",
            "Epicurus": "Epicurus was a Greek philosopher who founded the school of philosophy known as Epicureanism. He believed that the highest good was the pursuit of pleasure and the avoidance of pain.",
            "Seneca": "Seneca was a Roman philosopher and statesman. He wrote extensively on ethics, politics, and natural phenomena, and is known for his stoic philosophy.",
            "Lucretius": "Lucretius was a Roman poet and philosopher. He is best known for his epic poem 'De Rerum Natura', which expounds upon Epicurean philosophy.",
            "Plotinus": "Plotinus was a Roman philosopher and founder of Neoplatonism. He believed in the existence of a transcendent, all-encompassing reality.",
            "Zhuangzi": "Zhuangzi was a Chinese philosopher and writer. He is known for his Taoist philosophy and his collection of writings known as the 'Zhuangzi'.",
            "Confucius": "Confucius was a Chinese philosopher and teacher. He founded the school of thought known as Confucianism, which emphasizes moral values and social order.",
            "Laozi": "Laozi was a Chinese philosopher and writer. He is known for his Taoist philosophy and his work 'Tao Te Ching', which emphasizes the importance of humility and simplicity.",
            "Patanjali": "Patanjali was an Indian philosopher and scholar. He is known for his compilation of the Yoga Sutras, a seminal text on the practice of yoga and meditation.",
        },
        modern={
            "Friedrich Nietzsche": "Friedrich Nietzsche was a German philosopher, cultural critic, and poet. He wrote extensively on morality, religion, and the nature of human existence.",
            "Martin Heidegger": "Martin Heidegger was a German philosopher and one of the most important figures in 20th-century philosophy. He wrote extensively on ontology, existentialism, and phenomenology.",
            "Jean-Paul Sartre": "Jean-Paul Sartre was a French philosopher, playwright, and novelist. He is known for his work on existentialism, freedom, and the human condition.",
            "Simone De Beauvoir": "Simone de Beauvoir was a French writer and philosopher. She is known for her work on feminism, existentialism, and the nature of womanhood.",
            "Jacques Derrida": "Jacques Derrida was a French philosopher and one of the most important figures in postmodern philosophy. He wrote extensively on deconstruction, language, and meaning.",
            "Michel Foucault": "Michel Foucault was a French philosopher, social theorist, and historian of ideas. He is known for his work on power, knowledge, and social institutions.",
            "Gilles Deleuze": "Gilles Deleuze was a French philosopher and one of the most important figures in contemporary philosophy. He wrote extensively on ontology, metaphysics, and the nature of desire.",
            "Judith Butler": "Judith Butler is an American philosopher and gender theorist. She is known for her work on feminist theory, queer theory, and the politics of identity.",
            "Slavoj Zizek": "Slavoj Zizek is a Slovenian philosopher, cultural critic, and psychoanalytic theorist. He is known for his provocative and controversial work on ideology, politics, and culture.",
            "Cornel West": "Cornel West is an American philosopher, political activist, and public intellectual. He is known for his work on race, democracy, and social justice.",
        },
    ),
)
